// Series RLC circuit switched onto an AC source v_S = V̂ cos(ωt) at t = 0.
// The source is generated by two oscillator states (c, s) = (cos ωt, sin ωt), so the
// whole thing is one autonomous linear system and the matrix-exponential step is
// exact — no hold error on the sine, whatever the step size.
// States x = [i, v_C, c, s].

import { cabs, carg, cdiv, cmul, cx, type Complex } from '../core/linalg';
import { simulateFree } from '../core/lti';
import { rlcInfo, type RlcInfo } from './rlcSeries';
import type { Model, Params, Run } from './types';

export interface RlcAcInfo extends RlcInfo {
  omega: number; // drive, rad/s
  f0: number; // resonance, Hz
  Z: Complex; // R + j(ωL − 1/ωC)
  I: Complex; // steady-state current phasor (peak)
  VR: Complex;
  VL: Complex;
  VC: Complex;
  Q: number; // ω0 L / R
  bandwidth: number; // half-power bandwidth, Hz
  f1: number; // lower half-power frequency
  f2: number; // upper half-power frequency
}

export function rlcAcInfo(p: Params): RlcAcInfo {
  const { R, L, C, V, f } = p;
  const k = rlcInfo(p);
  const omega = 2 * Math.PI * f;
  const Z = cx(R, omega * L - 1 / (omega * C));
  const I = cdiv(cx(V), Z);
  const a = k.alpha;
  const root = Math.sqrt(a * a + k.omega0 * k.omega0);
  return {
    ...k,
    omega,
    f0: k.omega0 / (2 * Math.PI),
    Z,
    I,
    VR: cmul(cx(R), I),
    VL: cmul(cx(0, omega * L), I),
    VC: cmul(cx(0, -1 / (omega * C)), I),
    Q: (k.omega0 * L) / R,
    bandwidth: R / (2 * Math.PI * L),
    f1: (root - a) / (2 * Math.PI),
    f2: (root + a) / (2 * Math.PI),
  };
}

/** Instantaneous value of a phasor (peak convention): Re{X e^{jωt}}. */
export const inst = (X: Complex, omega: number, t: number) => cabs(X) * Math.cos(omega * t + carg(X));

const periodsOf = (p: Params) => {
  const k = rlcInfo(p);
  const T = 1 / p.f;
  const slowest = Math.min(...[k.s1, k.s2].map((s) => -s.re));
  // Long enough to watch the transient die out, short enough to still see each cycle.
  const settle = slowest > 1e-9 ? 6 / slowest : Infinity;
  return Math.min(120, Math.max(6, Math.ceil(settle / T)));
};

export const rlcAc: Model = {
  id: 'rlc-ac',

  poles(p) {
    const k = rlcInfo(p);
    return [k.s1, k.s2];
  },

  window(p) {
    return periodsOf(p) / p.f;
  },

  simulate(p, tEnd): Run {
    const { R, L, C, V, f } = p;
    const w = 2 * Math.PI * f;
    const n = Math.min(9000, Math.max(1600, Math.ceil(tEnd * f * 48)));
    const A = [
      [-R / L, -1 / L, V / L, 0],
      [1 / C, 0, 0, 0],
      [0, 0, 0, -w],
      [0, 0, w, 0],
    ];
    const { t, x } = simulateFree(A, [0, 0, 1, 0], tEnd, n);
    const [i, vC, c] = x;
    const k = rlcAcInfo(p);
    const vS = c.map((v) => V * v);
    const vR = i.map((v) => R * v);
    return {
      t,
      s: {
        i,
        vC,
        vS,
        vR,
        vL: i.map((_, j) => vS[j] - vR[j] - vC[j]),
        iss: t.map((tt) => inst(k.I, w, tt)),
        vCss: t.map((tt) => inst(k.VC, w, tt)),
      },
    };
  },
};

